#######DATABASE##################
app.datasource.jdbc-url=jdbc:postgresql://piaoserver.postgres.database.azure.com:5432/postgres
app.datasource.username=utentepiao
app.datasource.password=piaoSvil123
app.datasource.driver-class-name=org.postgresql.Driver
app.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

################Seconda connessione (autenticazione) ################
app.second-datasource.jdbc-url=jdbc:oracle:thin:@DBV033-scan.sogei.it:1521/DBV033_SRV_PDB_DFP
app.second-datasource.username=${ORACLE_USER_AUTH}
app.second-datasource.password=${ORACLE_PASSWORD_AUTH}
app.second-datasource.driver-class-name=oracle.jdbc.OracleDriver

######## AUTENTICAZIONE ################################
autenticazione.base-url=${API_AUTENTICAZIONE}
autenticazione.client-id=${AUTENTICAZIONE_CLIENT_ID}

########OPENTELEMETRY################################

## Configure exporter endpoints for traces and metrics
## Set the property based on the environment where you want to enable telemetry.
# 1 → All traces are sent. 0 → Telemetry is disabled.
management.tracing.sampling.probability=0

