# Usa un'immagine base leggera con Node.js (qui la versione 19 in ambiente Alpine)
FROM node:19-alpine

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia solo i file di definizione delle dipendenze per sfruttare la cache di Docker
COPY package*.json ./

# Installa le dipendenze in maniera pulita
RUN npm ci

# Copia il resto del codice sorgente nell'immagine
COPY . .

# Espone la porta (solitamente 3000 per le applicazioni React)
EXPOSE 3000

# Comando per avviare l'applicazione
CMD ["npm", "start"]