# Stage 1: Build dell'applicazione React
FROM node:18-alpine AS build
WORKDIR /app

# Copia solo i file necessari per installare le dipendenze
COPY package.json package-lock.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice sorgente
COPY . .

# Compila l'applicazione in modalità produzione
RUN npm run build

# Stage 2: Immagine runtime con Nginx
FROM nginx:alpine
# Copia la build dall'immagine precedente
COPY --from=build /app/build /usr/share/nginx/html
# Copia la configurazione custom di Nginx
#COPY nginx.conf /etc/nginx/conf.d/default.conf


# Espone la porta 80 (Nginx)
EXPOSE 80

# Comando di avvio di Nginx
CMD ["nginx", "-g", "daemon off;"]