#dev profile-specific property file

#######LOGGING OUTPUT FORMAT############
# Must be one of console,json
log.output.format=console
log.output.level=INFO
logging.level.software.amazon.awssdk=INFO

######FAULT-TOLERANCE#####################################
fault-utility.enable-fault-simulation=true

########JWT SECURITY################################
security.enable.jwt.configuration=false
security.skip.jwt.verification=true

########OPENTELEMETRY################################
management.defaults.metrics.export.enabled=false


######## CONFIGURAZIONI S3 ################################
spring.cloud.aws.s3.enabled=false
spring.cloud.aws.region.auto=false
aws.s3.endpoint=${S3_ENDPOINT}
aws.s3.bucket=${S3_BUCKET}
aws.s3.region=eu-west-1
aws.credentials.access-key=${S3_ACCESS_KEY}
aws.credentials.secret-key=${S3_SECRET_KEY}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

######## AUTENTICAZIONE ################################
autenticazione.base-url=${API_AUTENTICAZIONE}
autenticazione.client-id=${AUTENTICAZIONE_CLIENT_ID}


