package it.ey.enums;

public enum CodTipologiaAllegato {
    LOGO_ANAGRAFICA,
    ALLEGATO_SEZIONE,
    ANALISI_CONTESTO,
    VALORE_PUBBLICO,
    IMMAGINE_SEZIONE_21_1,
    IMMAGINE_SEZIONE_21_2,
    MANCATA_COMPILAZIONE,
    DOCUMENTAZIONE_MONITORAGGIO,
    IMMAGINE_SEZIONE_31,
    PIAO_PUBBLICAZIONE,
    APPROVAZIONE_PUBBLICAZIONE,
    RICHIESTA_APPROVAZIONE,
    ULTERIORI_ALLEGATI_PIAO,
    PIAO,
    HELP_DESK,
    PIAO_PDF_GENERATO,
    PIAO_EXCEL_GENERATO,
    AVVISI_DFP
}
