package it.ey.enums;

public enum CodTipologiaAllegato {
    LOGO_ANAGRAFICA, ALLEGATO_SEZIONE, ANALISI_CONTESTO, VALORE_PUBBLICO, IMMAGINE_SEZIONE_21_1,IMMAGINE_SEZIONE_21_2,MANCATA_COMPILAZIONE, DOCUMENTAZIONE_MONITORAGGIO
}
