package it.ey.enums;

public enum Ruolo {
    ROLE_SUPER_USER,
    ROLE_AMMINISTRATORE,
    ROLE_SUPERVISORE,
    ROLE_REFERENTE,
    ROLE_COORDINATORE_AMMINISTRATIVO,
    ROLE_VALIDATORE,
    ROLE_REDATTORE
}
