package it.ey.enums;

public enum Sezione {
    PIAO,
    SEZIONE_1,
    SEZIONE_21,
    SEZIONE_22,
    SEZIONE_21_INDICATORE,
    SEZIONE_22_ADEMPIMENTO,
    SEZIONE_23,
    SEZIONE_22_PERFOMANCE,
    SEZIONE_23_DATIPUBBLICATI,
    SEZIONE_23_ATTIVITASENSIBILE,
    SEZIONE_23_EVENTORISCHIO,
    SEZIONE_4

    }
