export enum CodTipologiaIndicatoreEnum {
  OVP = 'OVP',
  PERFORMANCE = 'PERFORMANCE',
  ACCESSI_DIGITALE = 'ACCESSI_DIGITALE',
  ACCESSI_FISICI = 'ACCESSI_FISICI',
  SEMPLIFICAZIONE = 'SEMPLIFICAZIONE',
  PARI_OPPORTUNITA = 'PARI_OPPORTUNITA',
  PERFORMANCE_ORGANIZZATIVA = 'PERFORMANCE_ORGANIZZATIVA',
  PERFORMANCE_INDIVIDUALE = 'PERFORMANCE_INDIVIDUALE',
  OBIETTIVO_PREVENZIONE = 'OBIETTIVO_PREVENZIONE', // Obiettivi prevenzione corruzione - Sezione 2.3
  MISURA_GENERALE = 'MISURA_GENERALE', // Misure generali di prevenzione - Sezione 2.3
  MISURA_PREVENZIONE = 'MISURA_PREVENZIONE', // Misure di prevenzione specifiche - Sezione 2.3
  OBIETTIVO_GENERALE = 'OBIETTIVO_GENERALE', // Obiettivi generali - Sezione 2.3
}
