export enum PiaoPDFStatusEnum {
  DA_GENERARE = 'DA_GENERARE',
  IN_GENERAZIONE = 'IN_GENERAZIONE',
  GENERATO = 'GENERATO',
  ERRORE_GENERAZIONE = 'ERRORE_GENERAZIONE',
  ANTIVIRUS = 'ANTIVIRUS',
  ANTIVIRUS_OK = 'ANTIVIRUS_OK',
  ANTIVIRUS_KO = 'ANTIVIRUS_KO',
}
