/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CustomHttpUrlEncodingCodec } from '../../config/encoder';
import { GenericResponse } from '../../models/interfaces/generic-response';
import { UserProfileDto } from './models';
import { Configuration } from '../../config/configuration';
import { Path } from '../../utils/path';

@Injectable()
export class ManagementUserControllerService {
  protected basePath = 'http://performance.test-securside.it/dfpperfutentiws/utenti';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() configuration: Configuration
  ) {
    if (Path.baseUrl()) {
      this.basePath = Path.baseUrl();
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = Path.baseUrl() || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   *
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerCreate(
    body: UserProfileDto,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerCreate(
    body: UserProfileDto,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerCreate(
    body: UserProfileDto,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerCreate(
    body: UserProfileDto,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error(
        'Required parameter body was null or undefined when calling managementUserControllerCreate.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<GenericResponse<any>>(
      'post',
      `${this.basePath}/management/user/create`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerDelete(
    id: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerDelete(
    id: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerDelete(
    id: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerDelete(
    id: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling managementUserControllerDelete.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'delete',
      `${this.basePath}/management/user/delete/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param name
   * @param surname
   * @param codiceFiscale
   * @param status
   * @param typology
   * @param page
   * @param size
   * @param sort
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', <any>name);
    }
    if (surname !== undefined && surname !== null) {
      queryParameters = queryParameters.set('surname', <any>surname);
    }
    if (codiceFiscale !== undefined && codiceFiscale !== null) {
      queryParameters = queryParameters.set('codiceFiscale', <any>codiceFiscale);
    }
    if (status !== undefined && status !== null) {
      queryParameters = queryParameters.set('status', <any>status);
    }
    if (typology !== undefined && typology !== null) {
      queryParameters = queryParameters.set('typology', <any>typology);
    }
    if (page !== undefined && page !== null) {
      queryParameters = queryParameters.set('page', <any>page);
    }
    if (size !== undefined && size !== null) {
      queryParameters = queryParameters.set('size', <any>size);
    }
    if (sort !== undefined && sort !== null) {
      queryParameters = queryParameters.set('sort', <any>sort);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/management/user/list`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerRetrieve(
    id: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerRetrieve(
    id: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerRetrieve(
    id: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerRetrieve(
    id: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling managementUserControllerRetrieve.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/management/user/retrieve/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerRetrieveAll(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerRetrieveAll(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerRetrieveAll(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerRetrieveAll(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/management/user/retrieve_all`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerRetrieveProfile(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerRetrieveProfile(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerRetrieveProfile(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerRetrieveProfile(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/management/user/retrieve_profile`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerRetrieveProfiles(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerRetrieveProfiles(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerRetrieveProfiles(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerRetrieveProfiles(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/management/user/retrieve_profiles`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   *
   *
   * @param body
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public managementUserControllerUpdate(
    body: UserProfileDto,
    id: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public managementUserControllerUpdate(
    body: UserProfileDto,
    id: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public managementUserControllerUpdate(
    body: UserProfileDto,
    id: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public managementUserControllerUpdate(
    body: UserProfileDto,
    id: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error(
        'Required parameter body was null or undefined when calling managementUserControllerUpdate.'
      );
    }

    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling managementUserControllerUpdate.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<GenericResponse<any>>(
      'put',
      `${this.basePath}/management/user/update/${encodeURIComponent(String(id))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
