export interface InlineResponse200 {
  status?: { id?: number; description?: string };
  data?: any;
}

export interface UserProfileDto {
  id?: number;
  username?: string;
  email?: string;
  nome?: string;
  cognome?: string;
  codiceFiscale?: string;
  roleType?: string;
  storedFileUuidPhoto?: string;
  [key: string]: any;
}

/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * DTO representing a user role and its associated privileges
 */
export interface RoleDto {
  /**
   * Role name
   */
  name: any;
  /**
   * Parent super-role name
   */
  superRoleName: any;
  /**
   * Typology of the role (e.g., PA, DFP)
   */
  typology: any;
  /**
   * List of privileges granted by this role
   */
  privileges: any;
}

/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Administration details within a user profile
 */
export interface AmministrazioneDto {
  /**
   * Administration unique identifier
   */
  id?: any;
  /**
   * Administration name
   */
  nome?: any;
  /**
   * IPA code
   */
  ipaCode?: any;
  /**
   * Contact phone in this administration
   */
  phone?: any;
  /**
   * User mobile phone
   */
  mobilePhone?: any;
  /**
   * Contact email in this administration
   */
  email?: any;
  /**
   * User qualification in this administration
   */
  qualifica?: any;
  /**
   * Supervisor name
   */
  supervisor?: any;
  /**
   * Supervisor fiscal code
   */
  supervisorFiscalCode?: any;
  /**
   * List of roles assigned to the user in this administration
   */
  ruoli: any;
}
