/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CustomHttpUrlEncodingCodec } from '../../config/encoder';
import { GenericResponse } from '../../models/interfaces/generic-response';
import { InlineResponse200, UserProfileDto } from './models';
import { Path } from '../../utils/path';
import { Configuration } from '../../config/configuration';

@Injectable({ providedIn: 'root' })
export class PublicUserAPIService {
  protected basePath = 'http://performance.test-securside.it/dfpperfutentiws/utenti';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() configuration: Configuration
  ) {
    if (Path.baseUrl()) {
      this.basePath = Path.baseUrl();
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = Path.baseUrl() || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Retrieve available roles
   * Returns list of available roles for user assignment. - **No typology**: All available roles. - **With typology**: Only roles matching PA or DFP.
   * @param typology Filter roles by typology (PA|DFP). Empty&#x3D;all available.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public publicRoleControllerRetrieveRoles(
    typology?: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<any>>;
  public publicRoleControllerRetrieveRoles(
    typology?: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GenericResponse<any>>>;
  public publicRoleControllerRetrieveRoles(
    typology?: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GenericResponse<any>>>;
  public publicRoleControllerRetrieveRoles(
    typology?: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (typology !== undefined && typology !== null) {
      queryParameters = queryParameters.set('typology', <any>typology);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<GenericResponse<any>>(
      'get',
      `${this.basePath}/public/role/retrieve`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * List public users with filters
   * Retrieves a paginated list of public users filtered by name, surname, email, tax code, status, and deletion status. Supports sorting and pagination.
   * @param name Filter by user first name
   * @param surname Filter by user surname
   * @param codiceFiscale Filter by codice fiscale
   * @param status Filter by user status (integer value): 1 for active users, 0 for inactive users.
   * @param typology Filter by user typology (string value): PA|DFP|OIV.
   * @param page Page number (zero-based)
   * @param size Page size
   * @param sort Sort criteria (format: field:asc|desc)
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public publicUserControllerPublicList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GenericResponse<UserProfileDto>>;
  public publicUserControllerPublicList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<InlineResponse200>>;
  public publicUserControllerPublicList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<InlineResponse200>>;
  public publicUserControllerPublicList(
    name?: any,
    surname?: any,
    codiceFiscale?: any,
    status?: any,
    typology?: any,
    page?: any,
    size?: any,
    sort?: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', <any>name);
    }
    if (surname !== undefined && surname !== null) {
      queryParameters = queryParameters.set('surname', <any>surname);
    }
    if (codiceFiscale !== undefined && codiceFiscale !== null) {
      queryParameters = queryParameters.set('codiceFiscale', <any>codiceFiscale);
    }
    if (status !== undefined && status !== null) {
      queryParameters = queryParameters.set('status', <any>status);
    }
    if (typology !== undefined && typology !== null) {
      queryParameters = queryParameters.set('typology', <any>typology);
    }
    if (page !== undefined && page !== null) {
      queryParameters = queryParameters.set('page', <any>page);
    }
    if (size !== undefined && size !== null) {
      queryParameters = queryParameters.set('size', <any>size);
    }
    if (sort !== undefined && sort !== null) {
      queryParameters = queryParameters.set('sort', <any>sort);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<InlineResponse200>('get', `${this.basePath}/public/user/list`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   * Retrieve authenticated user&#x27;s profile
   * Fetches the detailed profile information for the currently authenticated user using their user ID and amministrazione ID.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public publicUserControllerRetrieveProfile(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<InlineResponse200>;
  public publicUserControllerRetrieveProfile(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<InlineResponse200>>;
  public publicUserControllerRetrieveProfile(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<InlineResponse200>>;
  public publicUserControllerRetrieveProfile(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<InlineResponse200>(
      'get',
      `${this.basePath}/public/user/retrieve_profile`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Retrieve all profiles for authenticated user
   * Fetches all user profiles associated with the currently authenticated user.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public publicUserControllerRetrieveProfiles(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<InlineResponse200>;
  public publicUserControllerRetrieveProfiles(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<InlineResponse200>>;
  public publicUserControllerRetrieveProfiles(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<InlineResponse200>>;
  public publicUserControllerRetrieveProfiles(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<InlineResponse200>(
      'get',
      `${this.basePath}/public/user/retrieve_profiles`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
