export enum CodTipologiaAllegatoEnum {
  LOGO_ANAGRAFICA = 'LOGO_ANAGRAFICA',
  ALLEGATO_SEZIONE = 'ALLEGATO_SEZIONE',
  ANALISI_CONTESTO = 'ANALISI_CONTESTO',
  VALORE_PUBBLICO = 'VALORE_PUBBLICO',
  IMMAGINE_SEZIONE_21_1 = 'IMMAGINE_SEZIONE_21_1',
  IMMAGINE_SEZIONE_21_2 = 'IMMAGINE_SEZIONE_21_2',
  IMMAGINE_SEZIONE_31_1 = 'IMMAGINE_SEZIONE_31_1',
  MANCATA_COMPILAZIONE = 'MANCATA_COMPILAZIONE',
  DOCUMENTAZIONE_MONITORAGGIO = 'DOCUMENTAZIONE_MONITORAGGIO',
}
