export enum CodTipologiaValidazione {
  ACCETTA = 'ACCETTA',
  ANNULLA_INVIO = 'ANNULLA_INVIO',
  RIFIUTA = 'RIFIUTA',
  REVOCA = 'REVOCA',
  ACCETTA_SEZIONI = 'ACCETTA_SEZIONI',
  ACCETTA_PIAO = 'ACCETTA_PIAO',
}
