export enum CodTipologiaAllegatoEnum {
  LOGO_ANAGRAFICA = 'LOGO_ANAGRAFICA',
  ALLEGATO_SEZIONE = 'ALLEGATO_SEZIONE',
  ANALISI_CONTESTO = 'ANALISI_CONTESTO',
  VALORE_PUBBLICO = 'VALORE_PUBBLICO'
}
