export enum EventiNotificheEnum {
  HR_INC_BANDO_POSIZIONE_GIUNTO = 'HR_INC_BANDO_POSIZIONE_GIUNTO',
  HR_INC_BANDO_POSIZIONE_ASSEGNATO_EDRC = 'HR_INC_BANDO_POSIZIONE_ASSEGNATO_EDRC',
  HR_INC_PROPOSTA_INSERITA = 'HR_INC_PROPOSTA_INSERITA',
  HR_INC_PROPOSTA_APPROVATA = 'HR_INC_PROPOSTA_APPROVATA',
  HR_INC_PROPOSTA_RESPINTA = 'HR_INC_PROPOSTA_RESPINTA',
}
