export enum TipologiaObbiettivo {
  PERFORMANCE = 'PERFORMANCE',
  ACCESSI_DIGITALE = 'ACCESSI_DIGITALE',
  ACCESSI_FISICI = 'ACCESSI_FISICI',
  SEMPLIFICAZIONE = 'SEMPLIFICAZIONE',
  PARI_OPPORTUNITA = 'PARI_OPPORTUNITA',
  PERFORMANCE_ORGANIZZATIVA = 'PERFORMANCE_ORGANIZZATIVA',
  PERFORMANCE_INDIVIDUALE = 'PERFORMANCE_INDIVIDUALE',
}
