apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dfp-piao
  namespace: argocd
spec:
  description: Project for dfp-piao applications
  sourceRepos:
  - 'http://gitea-http.gitea.svc.cluster.local:3000/eyrepo/eyrepo.git'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'